# DO NOT EDIT THIS FILE. MAY CHANGE IN THE FUTURE.
# THIS FILE IS PART OF UNSTABLE RELEASE OF THE RUNTIME.
{
  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-26.05";
    impermanence.url = "github:nix-community/impermanence";
    impermanence.inputs.nixpkgs.follows = ""; # Only used in tests.
    impermanence.inputs.home-manager.follows = "";
  };

  outputs = { self, nixpkgs, impermanence, ... }: {
    packages = nixpkgs.lib.genAttrs [ "x86_64-linux" "aarch64-linux" ] (system: {
      claude-nixos = import ./claude-nixos.nix { pkgs = nixpkgs.legacyPackages.${system}; };
    });

    nixosModules.default = { config, lib, pkgs, ... }: {
      imports = [
        "${nixpkgs.outPath}/nixos/modules/profiles/qemu-guest.nix"
        impermanence.nixosModules.impermanence
      ];

      config = {
        boot.loader.external = { enable = true; installHook = "${pkgs.coreutils}/bin/true"; };
        # qemu-guest supplies the transport modules; load virtiofs for early mounts.
        boot.initrd.kernelModules = [ "virtiofs" ];

        # Boot.AgentSandbox
        assertions = [{
          assertion = lib.versionAtLeast config.boot.kernelPackages.kernel.version "6.19";
          message = "agentsandbox requires Linux 6.19+ for fuse.inval_wq.";
        }];
        boot.kernelPackages = pkgs.linuxPackages_latest;
        fileSystems."/" = { device = "none"; fsType = "tmpfs"; options = [ "mode=755" "nosuid" "nodev" "noexec" ]; };
        fileSystems."/nix" = { device = "nix"; fsType = "virtiofs"; options = [ "nosuid" "nodev" ]; };
        fileSystems."/home" = { device = "none"; fsType = "tmpfs"; options = [ "mode=755" "nosuid" "nodev" ]; neededForBoot = true; };
        systemd.mounts = [{
          what = "tmpfs";
          where = "/nix/var/nix/builds";
          type = "tmpfs";
          options = "mode=755,nosuid,nodev";
          wantedBy = [ "local-fs.target" ];
          unitConfig.ConditionKernelCommandLine = "agentsandbox.nested";
        }];
        systemd.services.agentsandbox-host-ca = {
          description = "Use the host CA bundle";
          wantedBy = [ "local-fs.target" ];
          before = [ "local-fs.target" ];
          after = [ "persistent.mount" ];
          unitConfig.ConditionKernelCommandLine = "agentsandbox.use-host-certs";
          serviceConfig = {
            Type = "oneshot";
            RemainAfterExit = true;
          };
          script = ''
            target="$(${pkgs.coreutils}/bin/readlink -f /etc/ssl/certs/ca-certificates.crt)"
            ${pkgs.util-linux}/bin/mount --bind /persistent/host-ca.crt "$target"
            ${pkgs.util-linux}/bin/mount -o remount,bind,ro "$target"
          '';
          preStop = ''
            target="$(${pkgs.coreutils}/bin/readlink -f /etc/ssl/certs/ca-certificates.crt)"
            ${pkgs.util-linux}/bin/umount "$target"
          '';
        };
        boot.kernel.sysctl."vm.overcommit_memory" = lib.mkDefault "1"; # Stability in low memory situations.
        systemd.services.fuse-inval-wq = {
          description = "Seed fuse.inval_wq before virtiofs mounts to free cached fds on host";
          wantedBy = [ "local-fs-pre.target" ];
          before = [ "local-fs-pre.target" "nix.mount" "persistent.mount" ];
          unitConfig.DefaultDependencies = false;
          serviceConfig.Type = "oneshot";
          script = ''
            ${pkgs.kmod}/bin/modprobe fuse
            if [ -w /sys/module/fuse/parameters/inval_wq ]; then
              echo 0 > /sys/module/fuse/parameters/inval_wq
              echo 5 > /sys/module/fuse/parameters/inval_wq
            fi
          '';
        };
        boot.kernelParams = [
          "panic=1" # Since we can't manually respond to a panic, just reboot.
          "boot.panic_on_fail" # Panics on boot failure.
          "systemd.journald.forward_to_console=1" # Show progress while running tests.
          "console=ttyS0,115200n8" # Used on `virsh console`.
        ];
        system.activationScripts.agentsandboxActivationGuard = ''
          if [ "$(readlink -f "$systemConfig")" != "$(readlink -f /nix/var/nix/profiles/system)" ]; then
            guard="$(mktemp /nix/var/nix/profiles/.agentsandbox-activation-guard.XXXXXX)" || {
              echo "agentsandbox: refusing activation while system profiles are read-only" >&2
              exit 1
            }
            rm -f "$guard"
          fi
        '';
        services.getty.autologinUser = "root";
        systemd.targets.agentsandbox-build = {
          description = "AgentSandbox build environment";
          wants = [ "dhcpcd.service" "sshd.service" "dbus.service" "serial-getty@ttyS0.service" ];
          after = [ "dhcpcd.service" ];
          unitConfig.AllowIsolate = true;
        };
        nix.settings.experimental-features = [ "nix-command" "flakes" ];

        # Users
        users.users.vscode = {
          # Used by ssh subcommand.
          isNormalUser = true;
        };

        # Service.OpenSSH, used by exec/ssh subcommand.
        security.pam.services.sshd.allowNullPassword = true;
        services.openssh = {
          enable = true;
          settings.PermitEmptyPasswords = true;
          settings.PermitRootLogin = "yes";
        };
        users.allowNoPasswordLogin = true;

        # Impermanence
        fileSystems."/persistent" = {
          neededForBoot = true;
          device = "persistent";
          fsType = "virtiofs";
          options = [ "nosuid" "nodev" ];
        };
        fileSystems."/workspace" = {
          device = "/persistent/workspace";
          fsType = "none";
          options = [ "bind" "nosuid" "nodev" ];
          depends = [ "/persistent" ];
        };
        environment.persistence."/persistent" = {
          directories = [
            "/var/lib/nixos" # Stable user/group id.
            "/var/lib/systemd" # systemd-creds host key.
          ];
          files = [
            # "/etc/machine-id" # kernel command line takes precedence.
            "/etc/ssh/ssh_host_ed25519_key"
          ];
        };
        services.openssh.hostKeys = [{ type = "ed25519"; path = "/etc/ssh/ssh_host_ed25519_key"; }];

        # Networking
        #networking.proxy.default = "http://10.0.2.2:3128";
        security.pki.certificates = [
          ''
            -----BEGIN CERTIFICATE-----
            MIIB6zCCAZGgAwIBAgIUaYGGUbLG+HkvXvXu3K82ADTaQKEwCgYIKoZIzj0EAwIw
            HzEdMBsGA1UEAwwUYWdlbnRzYW5kYm94LW1pdG0tY2EwHhcNMjYwNDE2MTIyOTQ4
            WhcNMzYwNDEzMTIyOTQ4WjAfMR0wGwYDVQQDDBRhZ2VudHNhbmRib3gtbWl0bS1j
            YTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABES2mEt0z0slKAmT5c8VjPiIupQ6
            BmDuvsV/2vxcJUW/JAjCoCv5dCdkMqQqx2W2cOqVK13QJlSpNANUlKY8DzKjgaow
            gacwHQYDVR0OBBYEFFxRZJh9Hi9yytkJ+J9m8H9iC3afMB8GA1UdIwQYMBaAFFxR
            ZJh9Hi9yytkJ+J9m8H9iC3afMA8GA1UdEwEB/wQFMAMBAf8wDgYDVR0PAQH/BAQD
            AgGGMBMGA1UdJQQMMAoGCCsGAQUFBwMBMC8GA1UdEQQoMCaCDmF1dGguZG9ja2Vy
            LmlvghRyZWdpc3RyeS0xLmRvY2tlci5pbzAKBggqhkjOPQQDAgNIADBFAiEAjxp4
            swt3eD19q8U5jb7en8Mqdk1i4V+uWRzo9lPafIwCIBHvmTTbmRRSZLtqzHzltolS
            hHRWTSDkZBTwOJ0bWEl7
            -----END CERTIFICATE-----
          ''
        ];

        # Optional firewall
        services.opensnitch.settings = {
          DefaultAction = "deny";
          InterceptUnknown = true;
          Server.Address = "10.0.2.2:50052";
        };

        # Minimize closure size i.e. ${nixpkgs}/nixos/modules/profiles/minimal.nix
        documentation.enable = lib.mkDefault false;
        documentation.doc.enable = lib.mkDefault false;
        documentation.info.enable = lib.mkDefault false;
        documentation.man.enable = lib.mkDefault false;
        documentation.nixos.enable = lib.mkDefault false;
        environment.defaultPackages = lib.mkDefault [ ];
        environment.stub-ld.enable = lib.mkDefault false;
        programs.command-not-found.enable = lib.mkDefault false;
        programs.fish.generateCompletions = lib.mkDefault false;
        services.logrotate.enable = lib.mkDefault false;
        services.udisks2.enable = lib.mkDefault false;
        xdg.autostart.enable = lib.mkDefault false;
        xdg.icons.enable = lib.mkDefault false;
        xdg.mime.enable = lib.mkDefault false;
        xdg.sounds.enable = lib.mkDefault false;
      };
    };
  };
}
